--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NetherByte233/NetherEconomy
build-by-default: true
branches:
- main
projects:
  NetherEconomy:
    path: ""
  
   icon: Icon.png
...
