https://poggit.pmmp.io/ci/NetherByte233/NetherEconomy
build-by-default: true
branches:
- main
projects:
  NetherEconomy:
    path: "src/NetherByte/NetherEconomy/NetherEconomy.php"
  
   icon: Icon.png
...
